-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Teleco"."Customer"
(
    "customerID" character varying NOT NULL,
    gender text,
    "SeniorCitizen" integer NOT NULL,
    "Partner" text,
    "Dependents" text,
    tenure integer,
    "Churn" text,
    PRIMARY KEY ("customerID")
);

CREATE TABLE IF NOT EXISTS "Teleco"."Service"
(
    service_id character varying NOT NULL,
    service_name character varying NOT NULL,
    contract character varying,
    PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS "Teleco"."Product"
(
    product_id character varying NOT NULL,
    product_name character varying,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS "Teleco"."Billing"
(
    "Billing_id" character varying NOT NULL,
    "PaperlessBilling" text NOT NULL,
    "PaymentMethod" character varying NOT NULL,
    "MonthlyCharges" double precision NOT NULL,
    "TotalCharges" double precision NOT NULL,
    PRIMARY KEY ("Billing_id")
);

CREATE TABLE IF NOT EXISTS "Teleco"."Support"
(
    support_id character varying NOT NULL,
    support_type character varying,
    PRIMARY KEY (support_id)
);

ALTER TABLE IF EXISTS "Teleco"."Customer"
    ADD FOREIGN KEY ("customerID")
    REFERENCES "Teleco"."Service" (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Teleco"."Customer"
    ADD FOREIGN KEY ("customerID")
    REFERENCES "Teleco"."Product" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Teleco"."Customer"
    ADD FOREIGN KEY ("customerID")
    REFERENCES "Teleco"."Support" (support_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Teleco"."Billing"
    ADD FOREIGN KEY ("Billing_id")
    REFERENCES "Teleco"."Customer" ("customerID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;